[project]
name = "ViralFactory"
version = "0.0.0"
description = "A tool to create viral content"
authors = [
    {name = "Paillat", email = "me@paillat.dev"},
]
dependencies = [
    "anthropic>=0.25.9",
    "google-api-python-client==2.48.0",
    "google-auth-oauthlib==1.2.0",
    "gradio>=4.31.3",
    "openai>=1.30.1",
    "orjson==3.10.3",
    "python-dotenv==1.0.1",
    "PyYAML==6.0.1",
    "Requests==2.31.0",
    "SQLAlchemy==2.0.29",
    "whisper-timestamped>=1.15.4",
    "moviepy @ git+https://github.com/OsaAjani/moviepy.git",
    "tiktok-uploader @ git+https://github.com/Paillat-dev/tiktok-uploader.git",
    "Google-Images-Search @ git+https://github.com/Paillat-dev/Google-Images-Search",
    "yt-dlp[default]==2023.11.16",
    "fix-busted-json==0.0.18",
    "TTS==0.22.0",
]

requires-python = "==3.10.*"
readme = "README.md"
license = {text = "AGPL-3.0"}


[tool.pdm.resolution.overrides]
numpy = ">=1.25.0"
typer = "<1.0,>=0.12.0"

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
lint = [
    "black"
]

[project.optional-dependencies]
win = [
    "windows-curses==2.3.2"
]

[tool.pdm.resolution]
respect-source-order = true

[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"
exclude_packages = ["torch", "torchvision", "torchaudio"]

[[tool.pdm.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
include_packages = ["torch", "torchvision", "torchaudio"]
exclude_packages = []

[tool.pdm.scripts]
start = "python main.py"
lint = "black ."
